- name: Cleanup task
  hosts: all
  become: true
  pre_tasks:

    - name: Remove index.html file
      ansible.builtin.file:
        path: /tmp/ansible.txt
        state: absent

- name: For develop env
  hosts: develop
  become: true
  roles:
    - develop

- name: For production env
  hosts: production
  become: true
  roles:
    - production
