- hosts: develop
  become: true
  pre_tasks:

  - name: Clean develop env
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

- name: For develop env
  hosts: develops
  become: true
  roles:
    - develop

- name: For production env
  hosts: production
  become: true
  roles:
    - production
