- name: Setup web server
  hosts: develop
  tasks:
    - name: Uninstall httpd if exists
      ansible.builtin.dnf:
        name:
          - httpd
        state: absent

    - name: Install httpd if exists
      ansible.builtin.dnf:
        name:
          - httpd
        state: present

    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Start httpd service
      ansible.builtin.copy:
        content: "Welcome to Ansible"
        dest: /var/www/html/index.html
        mode: '0644'
