- name: Setup web server
  hosts: develop
  tasks:
    - name: Create new user
      ansible.builtin.user:
        name: adam
        state: present
        shell: /bin/bash
        groups: wheel
        uid: 1010
        generate_ssh_keys:  true
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        append: true
