---
- name: Playbook_02
  hosts: develop
  tasks:
    - name: Task 01
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Fedora"  # This task will be execute, if condition is fulfill.

    - name: Task 02
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Ubuntu"  # This task will be execute, if condition is fulfill.

    - name: Task 03
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_distribution in ["Debian", "Mint"]  # This task will be execute, if ansible_distribution is Debian or Mint.

    - name: Task 04
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_distribution == "Fedora" and ansible_distribution_file_variety == "RedHat" ## This task will be execute, if it fulfill the both conditions.
